// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEUc7al4LO5iNX_i-Q1sTM2yrX44yytmE',
    appId: '1:772148163985:web:253d944a6aef22f319d630',
    messagingSenderId: '772148163985',
    projectId: 'wispin-999',
    authDomain: 'wispin-999.firebaseapp.com',
    storageBucket: 'wispin-999.firebasestorage.app',
    measurementId: 'G-M8KP27B56M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCViZn-T8iZfymASx3ED6YWxfqAiaJf0Es',
    appId: '1:772148163985:android:4e72e6416119570019d630',
    messagingSenderId: '772148163985',
    projectId: 'wispin-999',
    storageBucket: 'wispin-999.firebasestorage.app',
  );

}